# This file was generated by GoReleaser. DO NOT EDIT.
class Mnd < Formula
  desc "Magic number detector for Go"
  homepage "https://github.com/tommy-muehle/go-mnd"
  url "https://github.com/tommy-muehle/go-mnd/releases/download/1.1.0/go-mnd_1.1.0_darwin_amd64.tar.gz"
  version "1.1.0"
  sha256 "838d8b29a9f6f911068e64e27e54e6375745176e63ea8d6021ba86cb3b63da2c"

  def install
    bin.install "mnd"
  end

  test do
    system "#{bin}/mnd --version"
  end
end
